/*--------------------------------------------------------------------------------------\

CDM 4.1 HARVEST TABLE

\--------------------------------------------------------------------------------------*/

proc sql noprint;

create table cdm_out.HARVEST (compress=yes encrypt=aes encryptkey=&aeskey) as

SELECT 
    NETWORKID ,
    NETWORK_NAME ,
    DATAMARTID ,
    DATAMART_NAME ,
    DATAMART_PLATFORM ,
    CDM_VERSION ,
    DATAMART_CLAIMS ,
    DATAMART_EHR ,
    BIRTH_DATE_MGMT ,
    ENR_START_DATE_MGMT ,
    ENR_END_DATE_MGMT ,
    ADMIT_DATE_MGMT ,
    DISCHARGE_DATE_MGMT ,
    PX_DATE_MGMT ,
    RX_ORDER_DATE_MGMT ,
    RX_START_DATE_MGMT ,
    RX_END_DATE_MGMT ,
    DISPENSE_DATE_MGMT ,
    LAB_ORDER_DATE_MGMT ,
    SPECIMEN_DATE_MGMT ,
    RESULT_DATE_MGMT ,
    MEASURE_DATE_MGMT ,
    ONSET_DATE_MGMT ,
    REPORT_DATE_MGMT ,
    RESOLVE_DATE_MGMT ,
    PRO_DATE_MGMT ,
    DEATH_DATE_MGMT ,
    MEDADMIN_START_DATE_MGMT ,
    MEDADMIN_STOP_DATE_MGMT ,
    OBSCLIN_DATE_MGMT ,
    OBSGEN_DATE_MGMT ,
    INPUT( PUT(REFRESH_DEMOGRAPHIC_DATE , e8601da.) , e8601da.) AS REFRESH_DEMOGRAPHIC_DATE format date9. ,
    INPUT( PUT(REFRESH_ENROLLMENT_DATE , e8601da.) , e8601da.) AS REFRESH_ENROLLMENT_DATE format date9. ,
	INPUT( PUT(REFRESH_ENCOUNTER_DATE , e8601da.) , e8601da.) AS REFRESH_ENCOUNTER_DATE format date9. ,
    INPUT( PUT(REFRESH_DIAGNOSIS_DATE , e8601da.) , e8601da.) AS REFRESH_DIAGNOSIS_DATE format date9. ,
    INPUT( PUT(REFRESH_PROCEDURES_DATE , e8601da.) , e8601da.) AS REFRESH_PROCEDURES_DATE format date9. ,
    INPUT( PUT(REFRESH_VITAL_DATE , e8601da.) , e8601da.) AS REFRESH_VITAL_DATE format date9. ,
    INPUT( PUT(REFRESH_DISPENSING_DATE , e8601da.) , e8601da.) AS REFRESH_DISPENSING_DATE format date9. ,
	INPUT( PUT(REFRESH_LAB_RESULT_CM_DATE , e8601da.) , e8601da.) AS REFRESH_LAB_RESULT_CM_DATE format date9. ,
    INPUT( PUT(REFRESH_CONDITION_DATE , e8601da.) , e8601da.) AS REFRESH_CONDITION_DATE format date9. ,
    INPUT( PUT(REFRESH_PRO_CM_DATE , e8601da.) , e8601da.) AS REFRESH_PRO_CM_DATE format date9. ,
	INPUT( PUT(REFRESH_PRESCRIBING_DATE , e8601da.) , e8601da.) AS REFRESH_PRESCRIBING_DATE format date9. ,
    INPUT( PUT(REFRESH_PCORNET_TRIAL_DATE , e8601da.) , e8601da.) AS REFRESH_PCORNET_TRIAL_DATE format date9. ,
    INPUT( PUT(REFRESH_DEATH_DATE , e8601da.) , e8601da.) AS REFRESH_DEATH_DATE format date9. ,
    INPUT( PUT(REFRESH_DEATH_CAUSE_DATE , e8601da.) , e8601da.) AS REFRESH_DEATH_CAUSE_DATE format date9. ,
	INPUT( PUT(REFRESH_MED_ADMIN_DATE , e8601da.) , e8601da.) AS REFRESH_MED_ADMIN_DATE format date9. ,
    INPUT( PUT(REFRESH_OBS_CLIN_DATE , e8601da.) , e8601da.) AS REFRESH_OBS_CLIN_DATE format date9. ,
    INPUT( PUT(REFRESH_PROVIDER_DATE , e8601da.) , e8601da.) AS REFRESH_PROVIDER_DATE format date9. ,
	INPUT( PUT(REFRESH_OBS_GEN_DATE , e8601da.) , e8601da.) AS REFRESH_OBS_GEN_DATE format date9.
FROM cdm_in.HARVEST
;
