/*******************************************************************************
*  $Source: run_dce_report $;
*    $Date: 2016/04/01
*    Study: PCORnet
*
*  Purpose: Normalize the PCORnet data characterization query results and create the Empirical Data Characterization Report
* 
*  Inputs: 
*	   	1) SAS programs: /infolder/normalization.sas, dce_template.sas, dce_report.sas
		2) Excel spreadsheet:  toc_header_footer.xlsx
	  	3) Results of SAS query:  /drnoc/[DataMartID]_[Date]_data_characterization.cpt	
*
*  Outputs: 
*       1) Print of compiled Empirical Data Characterization report in RTF file format stored as
*                (<DataMart Id>_DCERPT_<response date>.rtf)
*
*
*  Requirements:  
*              1) Program runs in SAS 9.3 or higher
*              2) Each site is required to have previously created the following sub-directory 
*                   structure on its network/server. The subdirectories must 
*                   reside within an outer folder which contains the query name 
*                   from the DRN Query Tool (e.g. PROD_P02_DQA_FDPRO_DCQ_T1D3_c001_r001)
*                   a) /dmlocal: folder containing output generated by the 
*                       request that should be saved locally but not returned to
*                       DRN OC. 
*                   b) /drnoc: folder containing output generated by the request 
*                       that should be returned to the DRN OC. 
*                   c) /sasprograms: folder containing the master SAS programs 
*                       that must be edited and then executed locally.
*                   d) /infolder: folder containing all input and lookup files 
*                       needed to execute request. 
*
*  Actions needed: 
*               1) User places the run_dce_report.sas program in the sasprograms folder
*				2) User places dce_report.sas, normalization.sas, dcetemplate.sas and toc_header_footer.xls in the infolder folder
*				3) User provides their DATAMARTID  (section below)
*                     (Example: T1D3)
*               4) User provides root network/server paths where the required
*                     sub-directory structure has been created (section below) 
*                     (Example: /ct/pcornet/queries/PROD_P02_DQA_FDPRO_DCQ_T1D3_c001_r001/) 
*******************************************************************************/

********************************************************************************
* Provide user defined values
********************************************************************************;
 /*Enter DataMart ID:*/                                %let dmid=;
 /*Enter network/server directory: */                  %let qpath=/ct/pcornet_dc/queries/;
********************************************************************************
* End of user provided values
*******************************************************************************;

********************************************************************************
* Submit NORMALIZATION program
********************************************************************************;
%include "&qpath.infolder/normalization.sas";
********************************************************************************;

********************************************************************************
* Submit DCE report program
********************************************************************************;
%include "&qpath.infolder/dce_report.sas";
********************************************************************************;
